apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: example-task
  #  namespace: gitops tried this but access is wrong so will add to default for the operator
  #  namespace: openshift-operators tried this but still an access issue
spec:
  params:
    - name: appName
      type: string
  steps:
    - image: registry.redhat.io/ubi7/ubi-minimal
      command:
        - /bin/bash
        - '-c'
        - echo
        - $(inputs.params.appName)