apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
  namespace: tekton
spec:
  type: git
  params:
    - name: url
      value: https://github.com/edoatley/primes
    - name: revision
      value: master