apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: example-pipeline
  #  namespace: gitops tried this but access is wrong so will add to default for the operator
  #  namespace: openshift-operators tried this but still an access issue
spec:
  params:
    - name: appName
      description: The Application Name
      default: Unknown Application
  resources: []
  workspaces: []
  tasks:
    - name: example-task
      taskRef:
        kind: ClusterTask
        name: example-task
      params:
        - name: appName
          value: Override App Name