apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: primes-pipeline
  namespace: primes
spec:
  params:
    - name: IMAGE_NAME
      type: string
    - name: GIT_REPO
      type: string
    - name: GIT_REVISION
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: shared-workspace
          workspace: workspace
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"

    - name: build
      taskRef:
        kind: Task
        name: build-task
      workspaces:
        - name: shared-workspace
          workspace: workspace
      runAfter:
        - git-clone

    - name: cve-check
      taskRef:
        kind: Task
        name: cve-check-task
      workspaces:
        - name: shared-workspace
          workspace: workspace
      runAfter:
        - build

    - name: s2i
      taskRef:
        name: s2i-java
        kind: ClusterTask
      runAfter:
        - cve-check
      workspaces:
        - name: shared-workspace
          workspace: workspace
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: "false"

    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - s2i
      params:
        - name: SCRIPT
          value: |
            oc new-app --docker-image $(params.IMAGE_NAME)