apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: primes-pipeline
  namespace: primes
spec:
  params:
    - name: IMAGE_NAME
      type: string
    - name: GIT_REPO
      type: string
    - name: GIT_REVISION
      type: string
  workspaces:
    - name: source
    - name: build
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"

    - name: build
      taskRef:
        kind: Task
        name: build-task
      workspaces:
        - name: source
          workspace: source
        - name: build
          workspace: build
      runAfter:
        - git-clone

    - name: s2i
      taskRef:
        name: s2i-java
        kind: ClusterTask
      runAfter:
        - build
      workspaces:
        - name: workspace
          workspace: source
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: "false"

    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - s2i
      params:
        - name: SCRIPT
          value: |
            oc new-app --docker-image $(params.IMAGE_NAME)