kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ed-example
  namespace: example
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: ed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin