apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: git-clone-run-
  generation: 1
  namespace: tekton
spec:
  params:
  - name: url
    value: https://github.com/edoatley/primes.git
  - name: revision
    value: master
  serviceAccountName: "default"
  taskRef:
    kind: Task
    name: git-clone
  workspaces:
  - name: output
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
