apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: example-pipeline
  namespace: example
spec:
  params:
    - name: appName
      description: The Application Name
      default: Unknown Application
  resources: []
  workspaces: []
  tasks:
    - name: example-task
      taskRef:
        kind: Task
        name: example-task
      params:
        - name: appName
          value: Override App Name